apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-app-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: kenguru777/echo-server:latest
          ports:
            - containerPort: 8000
          env:
            - name: AUTHOR
              value: "Aleksey Arkhipov"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 3
      imagePullSecrets:
        - name: my-registry-secret
